/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.madlonkay.supertmxmerge.gui;

import java.util.List;
import javax.swing.Box;
import org.madlonkay.supertmxmerge.data.TmxInfo;
import org.madlonkay.supertmxmerge.data.DiffInfo;
import org.madlonkay.supertmxmerge.util.LocString;

    /**
 *
 * @author aaron.madlon-kay
 */
public class DiffWindow extends javax.swing.JFrame {

    /**
     * Creates new form MergeWindow
     */
    public DiffWindow(TmxInfo file1, TmxInfo file2, List<DiffInfo> diffs) {
        initComponents();
        file1Label.setText(file1.name);
        file1TextUnits.setText(LocString.getFormat("number_of_units", file1.textUnits));
        file2Label.setText(file2.name);
        file2TextUnits.setText(LocString.getFormat("number_of_units", file2.textUnits));
        for (DiffInfo info : diffs) {
            jPanel1.add(new DiffCell(info));
        }
        jPanel1.add(Box.createVerticalGlue());
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        controller = new org.madlonkay.supertmxmerge.DiffController();
        jPanel2 = new javax.swing.JPanel();
        file1Label = new javax.swing.JLabel();
        file2Label = new javax.swing.JLabel();
        file1TextUnits = new javax.swing.JLabel();
        file2TextUnits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${file1Name}"), file1Label, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(file1Label);

        file2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        file2Label.setText("Filename 2");
        jPanel2.add(file2Label);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controller, org.jdesktop.beansbinding.ELProperty.create("${file1SegmentCount}"), file1TextUnits, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(file1TextUnits);

        file2TextUnits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        file2TextUnits.setText("Segments 2");
        jPanel2.add(file2TextUnits);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.madlonkay.supertmxmerge.DiffController controller;
    private javax.swing.JLabel file1Label;
    private javax.swing.JLabel file1TextUnits;
    private javax.swing.JLabel file2Label;
    private javax.swing.JLabel file2TextUnits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
