/*
 * Copyright (C) 2013 Aaron Madlon-Kay <aaron@madlon-kay.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.madlonkay.supertmxmerge.gui;

import javax.swing.UIManager;
import javax.swing.border.TitledBorder;
import org.madlonkay.supertmxmerge.data.DiffInfo;
import org.madlonkay.supertmxmerge.util.LocString;

/**
 *
 * @author Aaron Madlon-Kay <aaron@madlon-kay.com>
 */
public class DiffCell extends javax.swing.JPanel {

    /**
     * Creates new form TUDiffCell
     */
    public DiffCell(int itemNumber, DiffInfo info) {
        initComponents();
        
        itemNumberLabel.setText(String.valueOf(itemNumber));
        sourceText.setText(info.sourceText);
        setSourceLanguage(info.sourceLanguage);
        setTargetLanguage(info.targetLanguage);
        setPreText(info.tuv1Text);
        setPostText(info.tuv2Text);
    }
    
    private void setSourceLanguage(String language) {
        TitledBorder sourceBorder = (TitledBorder) sourceTextPanel.getBorder();
        sourceBorder.setTitle(language);
    }
    
    private void setTargetLanguage(String language) {
        TitledBorder targetBorder = (TitledBorder) targetTargetPane.getBorder();
        targetBorder.setTitle(language);
    }
    
    private void setPreText(String text) {
        if (text == null) {
            tuvText1.setBackground(getBackground());
            text = LocString.get("tuv_not_present");
        }
        tuvText1.setText(text);
    }
    
    private void setPostText(String text) {
        if (text == null) {
            tuvText2.setBackground(getBackground());
            text = LocString.get("tuv_deleted");
        }
        tuvText2.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemNumberLabel = new javax.swing.JLabel();
        sourceTargetPane = new javax.swing.JSplitPane();
        sourceTextPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sourceText = new javax.swing.JTextArea();
        targetTargetPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuvText1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuvText2 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.BorderLayout());

        itemNumberLabel.setText("n");
        itemNumberLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        add(itemNumberLabel, java.awt.BorderLayout.WEST);

        sourceTargetPane.setBorder(null);
        sourceTargetPane.setDividerSize(0);
        sourceTargetPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        sourceTargetPane.setResizeWeight(0.5);

        sourceTextPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Source Language"));
        sourceTextPanel.setLayout(new javax.swing.BoxLayout(sourceTextPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        sourceText.setEditable(false);
        sourceText.setColumns(72);
        sourceText.setFont(UIManager.getDefaults().getFont("Label.font"));
        sourceText.setLineWrap(true);
        sourceText.setText("Source text");
        sourceText.setWrapStyleWord(true);
        jScrollPane3.setViewportView(sourceText);

        sourceTextPanel.add(jScrollPane3);

        sourceTargetPane.setTopComponent(sourceTextPanel);

        targetTargetPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Target Language"));
        targetTargetPane.setDividerSize(0);
        targetTargetPane.setResizeWeight(0.5);
        targetTargetPane.setMinimumSize(new java.awt.Dimension(1, 1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tuvText1.setEditable(false);
        tuvText1.setFont(UIManager.getDefaults().getFont("Label.font"));
        tuvText1.setLineWrap(true);
        tuvText1.setText("Target text 1");
        tuvText1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tuvText1);

        targetTargetPane.setLeftComponent(jScrollPane1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tuvText2.setEditable(false);
        tuvText2.setFont(UIManager.getDefaults().getFont("Label.font"));
        tuvText2.setLineWrap(true);
        tuvText2.setText("Target text 2");
        tuvText2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tuvText2);

        targetTargetPane.setRightComponent(jScrollPane2);

        sourceTargetPane.setBottomComponent(targetTargetPane);

        add(sourceTargetPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemNumberLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane sourceTargetPane;
    private javax.swing.JTextArea sourceText;
    private javax.swing.JPanel sourceTextPanel;
    private javax.swing.JSplitPane targetTargetPane;
    private javax.swing.JTextArea tuvText1;
    private javax.swing.JTextArea tuvText2;
    // End of variables declaration//GEN-END:variables

}
