/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.madlonkay.supertmxmerge.gui;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.madlonkay.supertmxmerge.IController;
import org.madlonkay.supertmxmerge.SuperTmxMerge;
import org.madlonkay.supertmxmerge.util.LocString;

/**
 *
 * @author amake
 */
public class FileSelectWindow extends javax.swing.JFrame {
    
    private final static Logger LOGGER = Logger.getLogger(FileSelectWindow.class.getName());
    
    /**
     * Creates new form FileSelectWindow
     */
    public FileSelectWindow() {
        initComponents();
    }

    private void promptChooseFile(JTextField target) {
        // Inspired by https://netbeans.org/kb/docs/java/gui-filechooser.html#config
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
              target.setText(file.getCanonicalPath());
            } catch (IOException ex) {
              LOGGER.log(Level.SEVERE,
                    LocString.getFormat("error_canonical_path", file.getAbsolutePath()), ex);
            }
        }
    }
    
    private IController getActiveController() {
        Component component = diffMergeTabbedPane.getSelectedComponent();
        if (component == diffPanel) {
            return diffController;
        } else if (component == mergePanel) {
            return mergeController;
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFileChooser1 = new javax.swing.JFileChooser();
        mergeController = new org.madlonkay.supertmxmerge.MergeController();
        diffController = new org.madlonkay.supertmxmerge.DiffController();
        diffMergeTabbedPane = new javax.swing.JTabbedPane();
        diffPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        file1Button = new javax.swing.JButton();
        file1Field = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        file2Button = new javax.swing.JButton();
        file2Field = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        mergePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        baseFileButton = new javax.swing.JButton();
        leftFileButton = new javax.swing.JButton();
        rightFileButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        baseFileField = new javax.swing.JTextField();
        leftFileField = new javax.swing.JTextField();
        rightFileField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jFileChooser1.setFileFilter(new FileNameExtensionFilter(LocString.get("tmx_file_type_label"), "tmx"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(LocString.get("file_select_window_title")); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mergeController, org.jdesktop.beansbinding.ELProperty.create("${actionType}"), diffMergeTabbedPane, org.jdesktop.beansbinding.BeanProperty.create("selectedIndex"));
        bindingGroup.addBinding(binding);

        diffPanel.setLayout(new java.awt.BorderLayout());
        diffPanel.add(filler1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        file1Button.setText(LocString.get("select_button_file1")); // NOI18N
        file1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file1ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(file1Button);

        file1Field.setColumns(20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, diffController, org.jdesktop.beansbinding.ELProperty.create("${file1}"), file1Field, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        bindingGroup.addBinding(binding);

        jPanel3.add(file1Field);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        file2Button.setText(LocString.get("select_button_file2")); // NOI18N
        file2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file2ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(file2Button);

        file2Field.setColumns(20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, diffController, org.jdesktop.beansbinding.ELProperty.create("${file2}"), file2Field, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        file2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file2FieldActionPerformed(evt);
            }
        });
        jPanel4.add(file2Field);

        jPanel1.add(jPanel4);

        diffPanel.add(jPanel1, java.awt.BorderLayout.CENTER);
        diffPanel.add(filler2, java.awt.BorderLayout.SOUTH);

        diffMergeTabbedPane.addTab(LocString.get("file_select_diff_tab"), diffPanel); // NOI18N

        mergePanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        baseFileButton.setText(LocString.get("select_button_base_file")); // NOI18N
        baseFileButton.setNextFocusableComponent(baseFileField);
        baseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseFileButtonActionPerformed(evt);
            }
        });
        jPanel7.add(baseFileButton);

        leftFileButton.setText(LocString.get("select_button_left_file")); // NOI18N
        leftFileButton.setNextFocusableComponent(leftFileField);
        leftFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftFileButtonActionPerformed(evt);
            }
        });
        jPanel7.add(leftFileButton);

        rightFileButton.setText(LocString.get("select_button_right_file")); // NOI18N
        rightFileButton.setNextFocusableComponent(rightFileField);
        rightFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFileButtonActionPerformed(evt);
            }
        });
        jPanel7.add(rightFileButton);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        baseFileField.setColumns(20);
        baseFileField.setNextFocusableComponent(leftFileButton);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mergeController, org.jdesktop.beansbinding.ELProperty.create("${baseFile}"), baseFileField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel8.add(baseFileField);

        leftFileField.setColumns(20);
        leftFileField.setNextFocusableComponent(rightFileButton);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mergeController, org.jdesktop.beansbinding.ELProperty.create("${leftFile}"), leftFileField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        leftFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftFileFieldActionPerformed(evt);
            }
        });
        jPanel8.add(leftFileField);

        rightFileField.setColumns(20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mergeController, org.jdesktop.beansbinding.ELProperty.create("${rightFile}"), rightFileField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        rightFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightFileFieldActionPerformed(evt);
            }
        });
        jPanel8.add(rightFileField);

        jPanel6.add(jPanel8);

        mergePanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        diffMergeTabbedPane.addTab(LocString.get("file_select_merge_tab"), mergePanel); // NOI18N

        getContentPane().add(diffMergeTabbedPane);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        okButton.setText(LocString.get("ok_button")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel5.add(okButton);

        cancelButton.setText(LocString.get("cancel_button")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel5.add(cancelButton);

        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void file2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file2FieldActionPerformed

    private void leftFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftFileFieldActionPerformed

    private void rightFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightFileFieldActionPerformed

    private void file1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file1ButtonActionPerformed
        promptChooseFile(file1Field);
    }//GEN-LAST:event_file1ButtonActionPerformed

    private void file2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file2ButtonActionPerformed
        promptChooseFile(file2Field);
    }//GEN-LAST:event_file2ButtonActionPerformed

    private void baseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseFileButtonActionPerformed
        promptChooseFile(baseFileField);
    }//GEN-LAST:event_baseFileButtonActionPerformed

    private void leftFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftFileButtonActionPerformed
        promptChooseFile(leftFileField);
    }//GEN-LAST:event_leftFileButtonActionPerformed

    private void rightFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightFileButtonActionPerformed
        promptChooseFile(rightFileField);
    }//GEN-LAST:event_rightFileButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        IController controller = getActiveController();
        if (controller.validateInput()) {
            controller.go();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baseFileButton;
    private javax.swing.JTextField baseFileField;
    private javax.swing.JButton cancelButton;
    private org.madlonkay.supertmxmerge.DiffController diffController;
    private javax.swing.JTabbedPane diffMergeTabbedPane;
    private javax.swing.JPanel diffPanel;
    private javax.swing.JButton file1Button;
    private javax.swing.JTextField file1Field;
    private javax.swing.JButton file2Button;
    private javax.swing.JTextField file2Field;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton leftFileButton;
    private javax.swing.JTextField leftFileField;
    private org.madlonkay.supertmxmerge.MergeController mergeController;
    private javax.swing.JPanel mergePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton rightFileButton;
    private javax.swing.JTextField rightFileField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
