/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.madlonkay.supertmxmerge.gui;

import javax.swing.border.TitledBorder;
import org.madlonkay.supertmxmerge.TuDiffInfo;

/**
 *
 * @author aaron.madlon-kay
 */
public class TuDiffCell extends javax.swing.JPanel {

    /**
     * Creates new form TUDiffCell
     */
    public TuDiffCell(TuDiffInfo info) {
        initComponents();
        
        sourceText.setText(info.sourceText);
        sourceText.setRows(sourceText.getLineCount());
        TitledBorder sourceBorder = (TitledBorder) sourceTargetPane.getBorder();
        sourceBorder.setTitle(info.sourceLanguage);
        TitledBorder targetBorder = (TitledBorder) targetTargetPane.getBorder();
        targetBorder.setTitle(info.targetLanguage);
        tuvText1.setText(info.tuv1Text);
        tuvText2.setText(info.tuv2Text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceTargetPane = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sourceText = new javax.swing.JTextArea();
        targetTargetPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuvText1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuvText2 = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        sourceTargetPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Source Language"));
        sourceTargetPane.setDividerSize(0);
        sourceTargetPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        sourceText.setEditable(false);
        sourceText.setLineWrap(true);
        sourceText.setText("Source text");
        sourceText.setWrapStyleWord(true);
        jScrollPane3.setViewportView(sourceText);

        sourceTargetPane.setTopComponent(jScrollPane3);

        targetTargetPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Target Language"));
        targetTargetPane.setDividerSize(0);
        targetTargetPane.setResizeWeight(0.5);
        targetTargetPane.setMinimumSize(new java.awt.Dimension(1, 1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tuvText1.setEditable(false);
        tuvText1.setLineWrap(true);
        tuvText1.setText("Target text 1");
        tuvText1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tuvText1);

        targetTargetPane.setLeftComponent(jScrollPane1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tuvText2.setEditable(false);
        tuvText2.setLineWrap(true);
        tuvText2.setText("Target text 2");
        tuvText2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tuvText2);

        targetTargetPane.setRightComponent(jScrollPane2);

        sourceTargetPane.setBottomComponent(targetTargetPane);

        add(sourceTargetPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane sourceTargetPane;
    private javax.swing.JTextArea sourceText;
    private javax.swing.JSplitPane targetTargetPane;
    private javax.swing.JTextArea tuvText1;
    private javax.swing.JTextArea tuvText2;
    // End of variables declaration//GEN-END:variables

}
