/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.madlonkay.supertmxmerge.gui;

import java.awt.Component;
import javax.swing.JList;
import org.madlonkay.supertmxmerge.TuDiffInfo;

/**
 *
 * @author aaron.madlon-kay
 */
public class TuDiffCell extends javax.swing.JPanel implements javax.swing.ListCellRenderer {

    /**
     * Creates new form TUDiffCell
     */
    public TuDiffCell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        sourceText = new javax.swing.JTextArea();
        targetLanguage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuvText1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuvText2 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1, 94));

        sourceText.setLineWrap(true);
        sourceText.setWrapStyleWord(true);
        jScrollPane3.setViewportView(sourceText);

        targetLanguage.setText("jLabel1");

        tuvText1.setLineWrap(true);
        tuvText1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tuvText1);

        tuvText2.setLineWrap(true);
        tuvText2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tuvText2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
            .addGroup(layout.createSequentialGroup()
                .addComponent(targetLanguage)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea sourceText;
    private javax.swing.JLabel targetLanguage;
    private javax.swing.JTextArea tuvText1;
    private javax.swing.JTextArea tuvText2;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        if (value instanceof TuDiffInfo) {
            TuDiffInfo diffInfo = (TuDiffInfo) value;
            sourceText.setText(diffInfo.sourceText);
            sourceText.setRows(sourceText.getLineCount());
            targetLanguage.setText(diffInfo.targetLanguage);
            tuvText1.setText(diffInfo.tuv1Text);
            tuvText2.setText(diffInfo.tuv2Text);
        }
        return this;
    }
}
